apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-service
          image: your-docker-repo/notification-service:latest # Replace with your Docker image
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: email-user
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: email-pass
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: twilio-account-sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: twilio-auth-token
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: twilio-phone-number
            - name: WEB_PUSH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: web-push-public-key
            - name: WEB_PUSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: web-push-private-key
            - name: KAFKA_BROKER
              value: "localhost:9092"
